//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccess.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpAccount { get; set; }
        public string EmpPassword { get; set; }
        public string EmpName { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public bool IsAccessDenied { get; set; }
        public string PostAccount { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string MdfAccount { get; set; }
        public Nullable<System.DateTime> MdfDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string OwnerAccount { get; set; }
        public bool IsEmailConfirmed { get; set; }
        public string EmailConfirmKey { get; set; }
        public bool PasswordHashed { get; set; }
        public Nullable<System.DateTime> EmailConfirmKeyDate { get; set; }
        public string PasswordResetKey { get; set; }
        public Nullable<System.DateTime> PasswordResetKeyDate { get; set; }
        public string DefaultRandomPassword { get; set; }
        public Nullable<System.DateTime> ThisLoginTime { get; set; }
        public string ThisLoginIP { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastLoginIP { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EmployeeRole EmployeeRole { get; set; }
    }
}
