//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.DataAccess.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchDataSource
    {
        public System.Guid ArticleId { get; set; }
        public System.Guid SubId { get; set; }
        public string CultureName { get; set; }
        public int SeqnoForCluster { get; set; }
        public string ArticleSubject { get; set; }
        public string ArticleContext { get; set; }
        public int ReadCount { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string BreadcrumbData { get; set; }
        public Nullable<System.Guid> Lv1ArticleId { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> MdfDate { get; set; }
    }
}
